CREATE TABLE IF NOT EXISTS CURRENCYEXCHANGE
(
    id           VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    fromCurrency VARCHAR NOT NULL,
    toCurrency   VARCHAR NOT NULL,
    exchangeRate FLOAT   NOT NULL
);
